// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/biz"
	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitHttpService(database Database) (*service.CustomerFollowHttpService, func(), error) {
	client, cleanup, err := NewClient(database)
	if err != nil {
		return nil, nil, err
	}
	customerFollowUseCase := biz.NewCustomerFollowUserCase(client)
	customerFollowHttpService := service.NewCustomerFollowService(customerFollowUseCase)
	return customerFollowHttpService, func() {
		cleanup()
	}, nil
}
