// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// CustomerFollow is the predicate function for customerfollow builders.
type CustomerFollow func(*sql.Selector)
