// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/ent/migrate"

	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/ent/customerfollow"

	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CustomerFollow is the client for interacting with the CustomerFollow builders.
	CustomerFollow *CustomerFollowClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CustomerFollow = NewCustomerFollowClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		CustomerFollow: NewCustomerFollowClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:         cfg,
		CustomerFollow: NewCustomerFollowClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CustomerFollow.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.CustomerFollow.Use(hooks...)
}

// CustomerFollowClient is a client for the CustomerFollow schema.
type CustomerFollowClient struct {
	config
}

// NewCustomerFollowClient returns a client for the CustomerFollow from the given config.
func NewCustomerFollowClient(c config) *CustomerFollowClient {
	return &CustomerFollowClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customerfollow.Hooks(f(g(h())))`.
func (c *CustomerFollowClient) Use(hooks ...Hook) {
	c.hooks.CustomerFollow = append(c.hooks.CustomerFollow, hooks...)
}

// Create returns a create builder for CustomerFollow.
func (c *CustomerFollowClient) Create() *CustomerFollowCreate {
	mutation := newCustomerFollowMutation(c.config, OpCreate)
	return &CustomerFollowCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomerFollow entities.
func (c *CustomerFollowClient) CreateBulk(builders ...*CustomerFollowCreate) *CustomerFollowCreateBulk {
	return &CustomerFollowCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomerFollow.
func (c *CustomerFollowClient) Update() *CustomerFollowUpdate {
	mutation := newCustomerFollowMutation(c.config, OpUpdate)
	return &CustomerFollowUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerFollowClient) UpdateOne(cf *CustomerFollow) *CustomerFollowUpdateOne {
	mutation := newCustomerFollowMutation(c.config, OpUpdateOne, withCustomerFollow(cf))
	return &CustomerFollowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerFollowClient) UpdateOneID(id int64) *CustomerFollowUpdateOne {
	mutation := newCustomerFollowMutation(c.config, OpUpdateOne, withCustomerFollowID(id))
	return &CustomerFollowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomerFollow.
func (c *CustomerFollowClient) Delete() *CustomerFollowDelete {
	mutation := newCustomerFollowMutation(c.config, OpDelete)
	return &CustomerFollowDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *CustomerFollowClient) DeleteOne(cf *CustomerFollow) *CustomerFollowDeleteOne {
	return c.DeleteOneID(cf.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *CustomerFollowClient) DeleteOneID(id int64) *CustomerFollowDeleteOne {
	builder := c.Delete().Where(customerfollow.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerFollowDeleteOne{builder}
}

// Query returns a query builder for CustomerFollow.
func (c *CustomerFollowClient) Query() *CustomerFollowQuery {
	return &CustomerFollowQuery{config: c.config}
}

// Get returns a CustomerFollow entity by its id.
func (c *CustomerFollowClient) Get(ctx context.Context, id int64) (*CustomerFollow, error) {
	return c.Query().Where(customerfollow.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerFollowClient) GetX(ctx context.Context, id int64) *CustomerFollow {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CustomerFollowClient) Hooks() []Hook {
	return c.hooks.CustomerFollow
}
