// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/ent/customerfollow"
	"github.com/fly-nick/Go-000/Week04/internal/customer_follow/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// CustomerFollowDelete is the builder for deleting a CustomerFollow entity.
type CustomerFollowDelete struct {
	config
	hooks    []Hook
	mutation *CustomerFollowMutation
}

// Where adds a new predicate to the delete builder.
func (cfd *CustomerFollowDelete) Where(ps ...predicate.CustomerFollow) *CustomerFollowDelete {
	cfd.mutation.predicates = append(cfd.mutation.predicates, ps...)
	return cfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cfd *CustomerFollowDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cfd.hooks) == 0 {
		affected, err = cfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CustomerFollowMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cfd.mutation = mutation
			affected, err = cfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cfd.hooks) - 1; i >= 0; i-- {
			mut = cfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfd *CustomerFollowDelete) ExecX(ctx context.Context) int {
	n, err := cfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cfd *CustomerFollowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: customerfollow.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: customerfollow.FieldID,
			},
		},
	}
	if ps := cfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cfd.driver, _spec)
}

// CustomerFollowDeleteOne is the builder for deleting a single CustomerFollow entity.
type CustomerFollowDeleteOne struct {
	cfd *CustomerFollowDelete
}

// Exec executes the deletion query.
func (cfdo *CustomerFollowDeleteOne) Exec(ctx context.Context) error {
	n, err := cfdo.cfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{customerfollow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cfdo *CustomerFollowDeleteOne) ExecX(ctx context.Context) {
	cfdo.cfd.ExecX(ctx)
}
