// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/entsql"
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// CustomerFollowColumns holds the columns for the "customer_follow" table.
	CustomerFollowColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "staff_id", Type: field.TypeInt64},
		{Name: "customer_id", Type: field.TypeInt64},
		{Name: "content", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "deleted", Type: field.TypeInt64},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true},
	}
	// CustomerFollowTable holds the schema information for the "customer_follow" table.
	CustomerFollowTable = &schema.Table{
		Name:        "customer_follow",
		Columns:     CustomerFollowColumns,
		PrimaryKey:  []*schema.Column{CustomerFollowColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
		Annotation:  &entsql.Annotation{Table: "customer_follow"},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomerFollowTable,
	}
)

func init() {
}
