// Code generated by entc, DO NOT EDIT.

package customerfollow

const (
	// Label holds the string label denoting the customerfollow type in the database.
	Label = "customer_follow"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStaffId holds the string denoting the staffid field in the database.
	FieldStaffId = "staff_id"
	// FieldCustomerId holds the string denoting the customerid field in the database.
	FieldCustomerId = "customer_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreateTime holds the string denoting the createtime field in the database.
	FieldCreateTime = "create_time"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldDeleteBy holds the string denoting the deleteby field in the database.
	FieldDeleteBy = "deleted_by"

	// Table holds the table name of the customerfollow in the database.
	Table = "customer_follow"
)

// Columns holds all SQL columns for customerfollow fields.
var Columns = []string{
	FieldID,
	FieldStaffId,
	FieldCustomerId,
	FieldContent,
	FieldCreateTime,
	FieldDeleted,
	FieldDeleteBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
